version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - scrum-poker-redis:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    container_name: redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - '8081:8081'

volumes:
  scrum-poker-redis: ~
