version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    container_name: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ['redis-server', '--requirepass', '$REDIS_PASSWORD']
    ports:
      - 6379:6379
    restart: always
    volumes:
      - scrum-poker-redis:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    container_name: redis-commander
    hostname: redis-commander
    restart: always
    environment:
      REDIS_HOST: 'redis'
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: ${HTTP_USER}
      HTTP_PASSWORD: ${HTTP_PASSWORD}
    ports:
      - '8081:8081'

volumes:
  scrum-poker-redis: ~
